name: 'Comment on PR'
description: 'Comment on PR'
inputs:
  folder-to-check:  # id of input
    description: 'Folder to trigger running on'
    required: true
  github-token:
    description: 'Secret github token'
    required: true
runs:
  using: "composite"
  steps:
    - name: Comment on PR
      uses: mshick/add-pr-comment@v1
      with:
        repo-token: ${{ inputs.github-token }}
        repo-token-user-login: 'github-actions[bot]'
        message: |
          ${{ inputs.folder-to-check }}