name: Plan / Test On PR

on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
    branches:
      - main

jobs:
  do_something:
    name: Do Stuff
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v2
      - run: ls .github/actions/comment-on-pr
      - id: foo
        uses: ./.github/actions/comment-on-pr
        with:
          folder-to-check: stage